Traceback (most recent call last):
  File "C:\Users\Bruger\Documents\Thesis\Road-Anomaly-Detector\road_anomaly_detector\main\model\main.py", line 142, in <module>
    main()
  File "C:\Users\Bruger\Documents\Thesis\Road-Anomaly-Detector\road_anomaly_detector\main\model\main.py", line 93, in main
    train_loader, val_loader,_ = get_data_loaders(config)
  File "C:\Users\Bruger\Documents\Thesis\Road-Anomaly-Detector\road_anomaly_detector\main\model\data_loader.py", line 175, in get_data_loaders
    for fname in os.listdir(image_dir) 
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Bruger/Documents/datasetz/datasets/cracktree200/Images'
